# Generated by Django 5.1.4 on 2024-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="tg_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID чата в Telegram"
            ),
        ),
    ]
