# Generated by Django 5.1.4 on 2024-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_tg_name_customuser_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="ID чата в Telegram"
            ),
        ),
    ]
