# Generated by Django 5.1.4 on 2024-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Выберете дату и время начала привычки",
                        null=True,
                        verbose_name="Время начала выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Выберете дату и время начала привычки",
                        max_length=255,
                        verbose_name="Время начала выполнения привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка является приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        choices=[
                            ("every day", "каждый день"),
                            ("every other day", "через день"),
                            ("every three days", "раз в 3 дня"),
                            ("every four days", "раз в 4 дня"),
                            ("every five days", "раз в 5 дней"),
                            ("every six days", "раз в 6 дней"),
                            ("every weak", "раз в неделю"),
                        ],
                        default="every day",
                        help_text="Выберите периодичность выполнения привычки",
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите предположительное время выполнения привычки в минутах",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать для общего доступа",
                        verbose_name="Общий доступ",
                    ),
                ),
            ],
        ),
    ]
