# Generated by Django 5.1.4 on 2024-12-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Опишите действие вашей привычки",
                max_length=255,
                verbose_name="Действие привычки",
            ),
        ),
    ]
